import type {Metadata} from "next";
import "./globals.css";
import Navbar from "@/components/navbar";
import ClientLayout from "@/components/client-layout";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className='antialiased'>
				<ClientLayout>{children}</ClientLayout>
			</body>
		</html>
	);
}
